# Generated by Django 5.2.16 on 2026-07-16 17:37

from __future__ import annotations

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="Diagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "diagram_type",
                    models.CharField(
                        choices=[
                            ("context", "Context"),
                            ("container", "Container"),
                            ("component", "Component"),
                            ("code", "Code"),
                        ],
                        max_length=30,
                    ),
                ),
                ("layout_data", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Stereotype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("is_edge", models.BooleanField(default=False)),
                ("property_schema", models.JSONField(default=dict)),
                ("allowed_edge_rules", models.JSONField(default=list)),
                ("color", models.CharField(blank=True, max_length=30)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="graph.package",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("properties", models.JSONField(default=dict)),
                ("owner", models.CharField(blank=True, max_length=200)),
                (
                    "health",
                    models.CharField(
                        choices=[("green", "Green"), ("yellow", "Yellow"), ("red", "Red")],
                        default="green",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("ratatosk", "Ratatosk"), ("human", "Human")],
                        default="human",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diagrams",
                    models.ManyToManyField(blank=True, related_name="elements", to="graph.diagram"),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elements",
                        to="graph.package",
                    ),
                ),
                (
                    "stereotype",
                    models.ForeignKey(
                        limit_choices_to={"is_edge": False},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="elements",
                        to="graph.stereotype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="diagram",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagrams",
                to="graph.package",
            ),
        ),
        migrations.CreateModel(
            name="YggdrasilModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "metamodel",
                    models.CharField(choices=[("c4", "C4")], default="c4", max_length=50),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_models",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="stereotype",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stereotypes",
                to="graph.yggdrasilmodel",
            ),
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("properties", models.JSONField(default=dict)),
                ("confidence", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="graph.element",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="graph.element",
                    ),
                ),
                (
                    "stereotype",
                    models.ForeignKey(
                        limit_choices_to={"is_edge": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships",
                        to="graph.stereotype",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="graph.yggdrasilmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="package",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="graph.yggdrasilmodel",
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="graph.yggdrasilmodel",
            ),
        ),
        migrations.AddField(
            model_name="diagram",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagrams",
                to="graph.yggdrasilmodel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stereotype",
            unique_together={("model", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="package",
            unique_together={("model", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="element",
            unique_together={("model", "slug")},
        ),
    ]
