# Generated by Django 5.2.16 on 2026-07-17 14:58

from __future__ import annotations

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("graph", "0003_metamodel_finalize_schema"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="stereotype",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Guidance for humans and Ratatosk LLM: when to use this stereotype.",
            ),
        ),
    ]
