# Generated by Django 5.1.15 on 2026-07-13 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(default='ratatosk', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('partial', 'Partial')], default='pending', max_length=16)),
                ('items', models.JSONField(default=list)),
                ('confidence_min', models.FloatField(default=0.0)),
                ('confidence_max', models.FloatField(default=1.0)),
                ('submitted_by', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stereotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('vertex', 'Vertex'), ('edge', 'Edge')], default='vertex', max_length=16)),
                ('property_schema', models.JSONField(blank=True, default=dict)),
                ('allowed_edges', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='graph.package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('ratatosk_run_id', models.CharField(blank=True, default='', max_length=64)),
                ('discovered_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('name', models.CharField(max_length=256)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_elements', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='graph.package')),
                ('stereotype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='graph.stereotype')),
            ],
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('cytoscape_layout', models.JSONField(blank=True, default=dict)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='graph.package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('ratatosk_run_id', models.CharField(blank=True, default='', max_length=64)),
                ('discovered_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('from_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='graph.element')),
                ('to_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='graph.element')),
                ('stereotype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='graph.stereotype')),
            ],
            options={
                'indexes': [models.Index(fields=['from_element', 'to_element'], name='graph_relat_from_el_0c9a56_idx'), models.Index(fields=['valid_from', 'valid_to'], name='graph_relat_valid_f_b575bf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['name'], name='graph_eleme_name_09a48d_idx'),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['valid_from', 'valid_to'], name='graph_eleme_valid_f_184827_idx'),
        ),
    ]
