# Generated by Django 5.2.16 on 2026-07-17 09:56

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar = [
        ("graph", "0001_initial_graph_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="ChangeSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("run_id", models.CharField(blank=True, max_length=50)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ratatosk", "Ratatosk"),
                            ("human", "Human"),
                            ("mcp", "MCP"),
                            ("rollback", "Rollback"),
                        ],
                        default="human",
                        max_length=20,
                    ),
                ),
                (
                    "review_mode",
                    models.CharField(
                        choices=[("auto", "Auto"), ("manual", "Manual")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("munin_reasoning", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_changesets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changesets",
                        to="graph.yggdrasilmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeSetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "op_type",
                    models.CharField(
                        choices=[
                            ("add_element", "Add Element"),
                            ("update_element", "Update Element"),
                            ("delete_element", "Delete Element"),
                            ("add_relationship", "Add Relationship"),
                            ("delete_relationship", "Delete Relationship"),
                            ("add_to_diagram", "Add to Diagram"),
                        ],
                        max_length=30,
                    ),
                ),
                ("detail", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "changeset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="changeset.changeset",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("changeset", "order")},
            },
        ),
        migrations.CreateModel(
            name="MuninRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rule_text", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_munin_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="munin_rules",
                        to="graph.yggdrasilmodel",
                    ),
                ),
                (
                    "source_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learned_rules",
                        to="changeset.changesetitem",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
